"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {buildTsmomPortfolio,SLOT_CAPITAL,MAX_POSITIONS,technicals,monthlyCloses}=require("../trading/bist-tsmom-service");

function bars(start=100, growth=1.01, count=280) { return Array.from({length:count},(_,index)=>{const date=new Date(Date.UTC(2024,0,index+1));const close=start*growth**index;return {timestamp:date.toISOString(),open:close,high:close*1.01,low:close*.99,close,volume:1000+index};}); }
function monthlyBars(start=100, growth=1.01) { return Array.from({length:14},(_,index)=>{const date=new Date(Date.UTC(2024,index,28));const close=start*growth**index;return {timestamp:date.toISOString(),open:close,high:close*1.01,low:close*.99,close,volume:1000};}); }
test("TSMOM ranks descending and stops at 30",()=>{const universe=Array.from({length:31},(_,i)=>`S${i}`);const histories=Object.fromEntries(universe.map((s,i)=>[s,monthlyBars(100,1.01+i*.001)]));const result=buildTsmomPortfolio({universe,histories,now:Date.UTC(2025,2,1)});assert.equal(result.summary.selectedCount,MAX_POSITIONS);assert.equal(result.rows.find(row=>row.tsmomRank===31).status,"POSITIVE_NOT_SELECTED");assert.ok(result.rows[0].tsmom>=result.rows[1].tsmom);});
test("fewer positives retain fixed slot capital and floor lots",()=>{const result=buildTsmomPortfolio({universe:["A","B"],histories:{A:monthlyBars(100,1.01),B:monthlyBars(100,.99)},now:Date.UTC(2025,2,1)});const a=result.rows.find(row=>row.symbol==="A");assert.equal(result.summary.selectedCount,1);assert.equal(a.targetSlotCapital,SLOT_CAPITAL);assert.equal(a.targetLot,Math.floor(SLOT_CAPITAL/a.currentPrice));assert.equal(a.status,"SELECTED");assert.equal(result.rows.find(row=>row.symbol==="B").status,"NEGATIVE");});
test("technical indicators do not alter selection",()=>{const result=buildTsmomPortfolio({universe:["A","B"],histories:{A:monthlyBars(100,1.02),B:monthlyBars(100,1.01)},now:Date.UTC(2025,2,1)});assert.equal(result.rows.find(row=>row.symbol==="A").status,"SELECTED");assert.equal(result.rows.find(row=>row.symbol==="B").status,"SELECTED");});
test("stale prices cannot create buys",()=>{const old=monthlyBars(100,1.02);const result=buildTsmomPortfolio({universe:["A"],histories:{A:old},now:Date.UTC(2030,0,1)});const row=result.rows[0];assert.equal(row.dataQuality,"STALE_PRICE");assert.equal(row.targetLot,0);assert.equal(row.requiredAction,"HOLD");});
test("rebalance sells before buys and uses delta lots",()=>{const histories={A:monthlyBars(100,.99),B:monthlyBars(100,1.02)};const result=buildTsmomPortfolio({universe:["A","B"],histories,positions:[{symbol:"A",quantity:8,entry:100,status:"OPEN"}],now:Date.UTC(2025,2,1)});assert.equal(result.rebalance.sells[0].symbol,"A");assert.equal(result.rebalance.buys[0].symbol,"B");});
test("rank 31 remains excluded even with strong technical values",()=>{const universe=Array.from({length:31},(_,index)=>`R${index}`);const histories=Object.fromEntries(universe.map((symbol,index)=>[symbol,monthlyBars(100,1.001+index*.0001)]));const result=buildTsmomPortfolio({universe,histories,now:Date.UTC(2025,2,1)});const row=result.rows.find(item=>item.tsmomRank===31);row.technical={rsi14:60,macd:999,sma20:1};assert.equal(row.status,"POSITIVE_NOT_SELECTED");});
test("selected rank remains selected regardless of informational technical fields",()=>{const result=buildTsmomPortfolio({universe:["R"],histories:{R:monthlyBars(100,1.02)},now:Date.UTC(2025,2,1)});const row=result.rows[0];row.technical={rsi14:5,macd:-99,sma20:999999};assert.equal(row.status,"SELECTED");});
test("residual cash is slot capital minus whole-lot value",()=>{const result=buildTsmomPortfolio({universe:["A"],histories:{A:monthlyBars(101,1.02)},now:Date.UTC(2025,2,1)});const row=result.rows[0];assert.equal(row.residualCashContribution,SLOT_CAPITAL-row.targetLot*row.executionReferencePrice);assert.ok(row.residualCashContribution>=0);});
test("no price history is explicitly NO_DATA",()=>{const result=buildTsmomPortfolio({universe:["EMPTY"],histories:{},now:Date.UTC(2025,2,1)});assert.equal(result.rows[0].status,"NO_DATA");assert.equal(result.rows[0].targetLot,0);});
test("technical calculation exposes known SMA and volume ratio",()=>{const series=Array.from({length:220},(_,index)=>({timestamp:new Date(Date.UTC(2024,0,index+1)).toISOString(),close:index+1,high:index+2,low:index,volume:100}));const result=technicals(series);assert.equal(result.sma20,210.5);assert.equal(result.averageVolume20,100);assert.equal(result.volumeRatio,1);});
test("incomplete current calendar month is not a TSMOM month-end",()=>{const series=[...monthlyBars(100,1.01),{timestamp:"2025-03-01T00:00:00.000Z",open:120,high:121,low:119,close:120,volume:1}];const months=monthlyCloses(series,Date.UTC(2025,2,15));assert.equal(months.at(-1).key,"2025-02");});
test("Yahoo-style time field is accepted for price timestamps",()=>{const source=monthlyBars(100,1.01).map(({timestamp,...bar})=>({...bar,time:Math.floor(new Date(timestamp).getTime()/1000)}));const result=buildTsmomPortfolio({universe:["A"],histories:{A:source},now:Date.UTC(2025,2,1)});assert.notEqual(result.rows[0].dataQuality,"NO_DATA");});
